DROP DATABASE IF EXISTS readme;
CREATE DATABASE readme
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE readme;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE posts (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  title CHAR(255) NOT NULL,
  user_id INT(11) UNSIGNED NOT NULL,
  content TEXT NOT NULL,
  views_count INT(11) UNSIGNED NOT NULL DEFAULT '0',
  category_id INT(11) UNSIGNED NOT NULL,
  hashtag_id INT(11) UNSIGNED NOT NULL DEFAULT '0',

  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (hashtag_id) REFERENCES hashtag (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE users (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email CHAR(255) NOT NULL UNIQUE,
  name CHAR(255) NOT NULL,
  password CHAR(255) NOT NULL,
  avatar_path CHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE comments (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INT(11) UNSIGNED NOT NULL,
  post_id INT(11) UNSIGNED NOT NULL,
  content TEXT NOT NULL,

  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE likes (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT(11) UNSIGNED NOT NULL,
  post_id INT(11) UNSIGNED NOT NULL,

  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE subs (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_who_id INT(11) UNSIGNED NOT NULL,
  user_on_whom_id INT(11) UNSIGNED NOT NULL,

  FOREIGN KEY (user_who_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_on_whom_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE messages (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  content TEXT NOT NULL,
  user_from_id INT(11) UNSIGNED NOT NULL,
  user_to_id INT(11) UNSIGNED NOT NULL,

  FOREIGN KEY (user_from_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_to_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE hashtag (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title CHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE categories (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name CHAR(255) NOT NULL
) ENGINE=InnoDB;
